export enum Tag {
  TAG_UNSPECIFIED,
  TAG_THAI_FOOD,
  TAG_DESSERT,
  TAG_KOREAN_FOOD,
  TAG_JAPANESE_FOOD,
  TAG_CHINESE_FOOD,
  TAG_SEA_FOOD,
  TAG_VEGAN_FOOD,
  TAG_HEALTHY_FOOD,
  TAG_BEVERAGE,
  TAG_ESAN_FOOD,
}

export enum DeliveryType {
  DELIVERY_TYPE_UNSPECIFIED,
  DELIVERY_TYPE_BIG_C,
  DELIVERY_TYPE_LOTUS,
}
